var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__09~gvxo._.js")
R.c("server/chunks/ssr/node_modules_0_ce7g1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0v9w~pw.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-q7811._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/_0u4n_ia._.js")
R.c("server/chunks/ssr/app_loading_tsx_05semg5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_login_page_actions_02kefem.js")
R.m(89696)
module.exports=R.m(89696).exports
